service: flask-serverless

provider:
  name: aws
  runtime: python3.12
  region: us-east-2

functions:
  app:
    handler: wsgi.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: run.app  # Function to create the Flask app
    packRequirements: false  # Allow Serverless to package requirements without Docker

package:
  exclude:
    - node_modules/**
    - venv/**
    - tests/**  # Optional: Exclude test folders if not needed

requirements:
  dockerizePip: true